# Site settings
# in the templates available like {{ site.myvariable }}.
title: Clean portfolio theme for Jekyll powered by Bootstrap 4.
email: h648637692@gmail.com
brand: Hu Han
headline: Inventor, Engineer and Futurist
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.tonyhu.cn" # the base hostname & protocol for your site
copyright: 2017. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: h648637692@gmail.com
phone: +86 188-5004-6315

# Tracking
googleAnalitycsID: UA-83933844-1

